In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import math

In [3]:
###Set constants and parameters

##input params
H = 0.42 #no units,ratio #Hematocrit assumed to be constant
M = 20e-9 #mol_ O2/(mL/s) #Taken from table 2 from Wiley Payne paper
cHb = 0.2 #mL_O2/m #Taken from table 2 from Wiley Payne paper
paO2_bar_t = 15 #mmHG #Taken from table 2 from Wiley Payne paper

##SI them
M = M*10e3
cHb = cHb*10e-3
paO2_bar_t = paO2_bar_t*133.322

###Set up input data

##reset df
df = None

##Input data
#all data taken from Payne article
df = pd.DataFrame({'Name': ['A1', 'A2', 'A3', 'A4', 'A5', 'A6', 'C', 'V6', 'V5', 'V4', 'V3', 'V2', 'V1'], 
                   'Number': [1, 2, 4, 8, 16, 32, 64, 32, 16, 8, 4, 2, 1],
                   'Diameter(µm)': [23.97, 19.17, 15.28, 12.08, 9.46, 7.32, 8, 11.51, 14.53, 17.79, 21.45, 25.70, 30.77],
                   'Length(µm)': [1267.6, 930.3, 543.6, 302.3, 161.2, 154.7, 243.9, 473.9, 272.3, 426.6, 632.5, 844.2, 936.3],
                   'Viscocity(mPAs)': [1.59, 1.50, 1.42, 1.34, 1.28, 1.23, 1.24, 1.33, 1.40, 1.48, 1.55, 1.62, 1.7],
                   'Pressure Drop(mmHg)': [6.93, 5.87, 4.02, 2.70, 1.82, 2.35, 2.62, 1.27, 0.61, 0.89, 1.31, 1.78, 2.01],
                   'Saturation': [0.94, 0.93, 0.92, 0.89, 0.84, 0.765, 0.665, 0.61, 0.5975, 0.5875, 0.5825, 0.5775, 0.5725]})

##change units
df['Diameter(µm)'] = df['Diameter(µm)']*1e-6
df['Length(µm)'] = df['Length(µm)']*1e-6
df['Viscocity(mPAs)'] = df['Viscocity(mPAs)']*1e-3
df['Pressure Drop(mmHg)'] = df['Pressure Drop(mmHg)']*133.322
##rename the titles for the units
df = df.rename(columns={'Diameter(µm)':'Diameter(m)', 'Length(µm)':'Length(m)', 'Viscocity(mPAs)':'Viscocity(PAs)', 'Pressure Drop(mmHg)':'Pressure Drop(Pa)'})

###Calculate Flows

##Calculate resitances of each single vessel for each type
df['Resistance for U'] = 32 * df['Viscocity(PAs)'] * df['Length(m)'].div(df['Diameter(m)']**2)
df['Resistance for Q'] = 128 * df['Viscocity(PAs)'] * df['Length(m)'].div(math.pi*(df['Diameter(m)']**4))

##Alter resistances for C
#These are aross each pressure drop (explains the doubled resistance for the capillaries as in paralell so have half the flow each (flow is shared))
df.loc[df.index[df['Name'] == 'C'][0],'Resistance for U'] = df.loc[df.index[df['Name'] == 'C'][0],'Resistance for U']*2
df.loc[df.index[df['Name'] == 'C'][0],'Resistance for Q'] = df.loc[df.index[df['Name'] == 'C'][0],'Resistance for Q']*2

##Calculate flow in a single vessel
df['U in single(m/s)'] = df['Pressure Drop(Pa)'].div(df['Resistance for U'])
df['Q in single(m^3/s)'] = df['Pressure Drop(Pa)'].div(df['Resistance for Q'])

In [4]:
###Next stage

##Calculate Vt
df['Vt'] = df['Q in single(m^3/s)']*cHb*H*df['Saturation']/M
#This will remain fixed.

##

In [5]:
df

,Name,Number,Diameter(m),Length(m),Viscocity(PAs),Pressure Drop(Pa),Saturation,Resistance for U,Resistance for Q,U in single(m/s),Q in single(m^3/s),Vt
0,A1,1,0.000024,0.001268,0.00159,923.92146,0.9400,112251.787408,2.487524e+14,0.008231,3.714221e-12,1.466374e-11
1,A2,2,0.000019,0.000930,0.00150,782.60014,0.9300,121512.241594,4.210037e+14,0.006441,1.858891e-12,7.260829e-12
2,A3,4,0.000015,0.000544,0.00142,535.95444,0.9200,105796.441983,5.769451e+14,0.005066,9.289523e-13,3.589472e-12
3,A4,8,0.000012,0.000302,0.00134,359.96940,0.8900,88829.875883,7.750600e+14,0.004052,4.644407e-13,1.736079e-12
4,A5,16,0.000009,0.000161,0.00128,242.64604,0.8400,73780.690031,1.049713e+15,0.003289,2.311547e-13,8.155136e-13
5,A6,32,0.000007,0.000155,0.00123,313.30670,0.7650,113637.910956,2.700295e+15,0.002757,1.160268e-13,3.727943e-13
6,C,64,0.000008,0.000244,0.00124,349.30364,0.6650,302436.000000,6.016773e+15,0.001155,5.805498e-14,1.621476e-13
7,V6,32,0.000012,0.000474,0.00133,169.31894,0.6100,152243.121797,1.463178e+15,0.001112,1.157200e-13,2.964746e-13
8,V5,16,0.000015,0.000272,0.00140,81.32642,0.5975,57782.247044,3.484764e+14,0.001407,2.333772e-13,5.856600e-13
9,V4,8,0.000018,0.000427,0.00148,118.65658,0.5875,63838.202298,2.568259e+14,0.001859,4.620117e-13,1.140014e-12
10,V3,4,0.000021,0.000632,0.00155,174.65182,0.5825,68184.806646,1.886875e+14,0.002561,9.256141e-13,2.264515e-12
11,V2,2,0.000026,0.000844,0.00162,237.31316,0.5775,66258.880528,1.277285e+14,0.003582,1.857949e-12,4.506456e-12
12,V1,1,0.000031,0.000936,0.00170,267.97722,0.5725,53797.108111,7.234592e+13,0.004981,3.704110e-12,8.906531e-12